#!/usr/bin/env python
# Tool to distribute all datasets on dCache - uses simple greedy algorithm
# by Fred Stober (stober@cern.ch)

import sys, os, copy
from toolKIT.utils import expath, progress, get_cached
from toolKIT.chimera import dCacheInfo, get_chimera_data
from toolKIT.dCache import get_pool_infos
from toolKIT.dCache_distribute import filterMoveable, writeTransferCommands, writeTransferFile
from toolKIT.lfntools import fn2ddn
from toolKIT.monitoring import happyface_upload

dCacheWebHost = 'http://192.108.45.36:2288'

# Play back old storage 
#from toolKIT.chimera import cache_chimera_data
#cache_chimera_data(expath('~/storage_scratch/chimera-dump'),
#	expath('~/storage_scratch/storage-information'), 201407160705)
chimera_path = expath('~/storage_scratch/chimera-dump/current')
